<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Director extends \AppBundle\Entity\Director implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'secondName', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'thirdName', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'dateStartWork', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'salary', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'worker'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'secondName', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'thirdName', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'position', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'dateStartWork', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'salary', '' . "\0" . 'AppBundle\\Entity\\Director' . "\0" . 'worker'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Director $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecondName($secondName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecondName', [$secondName]);

        return parent::setSecondName($secondName);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecondName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecondName', []);

        return parent::getSecondName();
    }

    /**
     * {@inheritDoc}
     */
    public function setThirdName($thirdName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setThirdName', [$thirdName]);

        return parent::setThirdName($thirdName);
    }

    /**
     * {@inheritDoc}
     */
    public function getThirdName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getThirdName', []);

        return parent::getThirdName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateStartWork($dateStartWork)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateStartWork', [$dateStartWork]);

        return parent::setDateStartWork($dateStartWork);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStartWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStartWork', []);

        return parent::getDateStartWork();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalary($salary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalary', [$salary]);

        return parent::setSalary($salary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalary', []);

        return parent::getSalary();
    }

    /**
     * {@inheritDoc}
     */
    public function setWorker(\AppBundle\Entity\Worker $worker = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWorker', [$worker]);

        return parent::setWorker($worker);
    }

    /**
     * {@inheritDoc}
     */
    public function getWorker()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWorker', []);

        return parent::getWorker();
    }

}
