<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container16o1b1l\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container16o1b1l/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container16o1b1l.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container16o1b1l\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container16o1b1l\appDevDebugProjectContainer(array(
    'container.build_hash' => '16o1b1l',
    'container.build_id' => '80c92943',
    'container.build_time' => 1531304387,
), __DIR__.\DIRECTORY_SEPARATOR.'Container16o1b1l');
